import {
  SiReact,
  SiTypescript,
  SiJavascript,
  SiHtml5,
  SiTailwindcss,
  SiFramer,
  SiRedux,
  SiReactquery,
  SiMui,
  SiStyledcomponents,
  SiSass,
  SiVite,
  SiNodedotjs,
  SiExpress,
  SiGraphql,
  SiMongodb,
  SiPostgresql,
  SiRedis,
  SiSocketdotio,
  SiWebrtc,
  SiJsonwebtokens,
  SiGooglecloud,
  SiOpenai,
  SiCloudinary,
  SiStripe,
  SiGithubactions,
  SiGit,
  SiPostman,
  SiLinux,
  SiJest,
  SiTestinglibrary,
  SiDocker,
  SiKubernetes,
} from "react-icons/si";

import {
  FaEye,
  FaLock,
  FaLink,
  FaTools,
  FaComments,
  FaUsers,
  FaProjectDiagram,
  FaPuzzlePiece,
  FaServer,
  FaRoute,
  FaCloud,
} from "react-icons/fa";

import { TbApi } from "react-icons/tb";
import { MdArchitecture } from "react-icons/md";

export const SkillCategories = {
  Frontend: [
    { label: "React.js",          icon: SiReact,            color: "#61DAFB" },
    { label: "TypeScript",        icon: SiTypescript,       color: "#3178C6" },
    { label: "JavaScript",        icon: SiJavascript,       color: "#F7DF1E" },
    { label: "HTML & CSS",        icon: SiHtml5,            color: "#E44D26" },
    { label: "TailwindCSS",       icon: SiTailwindcss,      color: "#38BDF8" },
    { label: "Framer Motion",     icon: SiFramer,           color: "#a855f7" },
    { label: "Redux Toolkit",     icon: SiRedux,            color: "#764ABC" },
    { label: "Zustand",           icon: FaTools,            color: "#6c63ff" },
    { label: "React Query",       icon: SiReactquery,       color: "#FF4154" },
    { label: "Fluent UI",         icon: SiMui,              color: "#0078D4" },
    { label: "Material-UI",       icon: SiMui,              color: "#007FFF" },
    { label: "Chakra-UI",         icon: SiReact,            color: "#319795" },
    { label: "React-Bootstrap",   icon: SiReact,            color: "#7952B3" },
    { label: "Styled Components", icon: SiStyledcomponents, color: "#DB7093" },
    { label: "Sass",              icon: SiSass,             color: "#CC6699" },
    { label: "React Router",      icon: FaRoute,            color: "#CA4245" },
    { label: "Vite",              icon: SiVite,             color: "#646CFF" },
  ],
  Backend: [
    { label: "Node.js",     icon: SiNodedotjs,     color: "#339933" },
    { label: "Express.js",  icon: SiExpress,       color: "#9090b0" },
    { label: "GraphQL",     icon: SiGraphql,       color: "#E10098" },
    { label: "REST APIs",   icon: TbApi,           color: "#6c63ff" },
    { label: "MVC Pattern", icon: MdArchitecture,  color: "#a855f7" },
    { label: "SSR with EJS",icon: FaServer,        color: "#9090b0" },
    { label: "MongoDB",     icon: SiMongodb,       color: "#47A248" },
    { label: "PostgreSQL",  icon: SiPostgresql,    color: "#336791" },
    { label: "Redis",       icon: SiRedis,         color: "#DC382D" },
    { label: "Socket.IO",   icon: SiSocketdotio,   color: "#f0f0ff" },
    { label: "WebRTC",      icon: SiWebrtc,        color: "#333333" },
    { label: "JWT / RBAC",  icon: SiJsonwebtokens, color: "#d63aff" },
    { label: "bcrypt",      icon: FaLock,          color: "#6c63ff" },
    { label: "Mongoose",    icon: FaLink,          color: "#880000" },
  ],
  "Cloud & AI": [
    { label: "Google Vertex AI",  icon: SiGooglecloud,        color: "#4285F4" },
    { label: "Vision AI (OCR)",   icon: FaEye,                color: "#34A853" },
    { label: "OpenAI API",        icon: SiOpenai,             color: "#f0f0ff" },
    { label: "Cloudinary",        icon: SiCloudinary,         color: "#3448C5" },
    { label: "Stripe",            icon: SiStripe,             color: "#635BFF" },
    { label: "Azure DevOps",      icon: FaCloud,          color: "#0078D7" },
    { label: "SharePoint FX",     icon: FaServer,         color: "#038387" },
  ],
  "Testing & Tools": [
    { label: "Playwright",           icon: SiTestinglibrary, color: "#2EAD33" },
    { label: "Jest",                 icon: SiJest,           color: "#C21325" },
    { label: "React Testing Library",icon: SiTestinglibrary, color: "#E33332" },
    { label: "Supertest",            icon: FaTools,          color: "#6c63ff" },
    { label: "Docker",               icon: SiDocker,         color: "#2496ED" },
    { label: "Kubernetes",           icon: SiKubernetes,     color: "#326CE5" },
    { label: "CI/CD",                icon: SiGithubactions,  color: "#2088FF" },
    { label: "Git & GitHub",         icon: SiGit,            color: "#F05032" },
    { label: "Postman",              icon: SiPostman,        color: "#FF6C37" },
    { label: "Linux",                icon: SiLinux,          color: "#FCC624" },
  ],
  "Soft Skills": [
    { label: "System Design",       icon: FaProjectDiagram, color: "#a855f7" },
    { label: "Problem-Solving",     icon: FaPuzzlePiece,    color: "#6c63ff" },
    { label: "Strong Communication",icon: FaComments,       color: "#38BDF8" },
    { label: "Team Leadership",     icon: FaUsers,          color: "#4ade80" },
  ],
};

// backward compat
export const Skills = Object.values(SkillCategories).flat().map((s) => s.label);