export const Skills= ["React.Js",
  "Node (Node Js)",
  "Express (Express Js)",
  "JavaScript",
  "TypeScript",
  "MongoDB",
  "Mongoose",
  "Git",
  "Postman",
  "Redux-Toolkit",
  "jsonwebtoken (JWT-based authentication)",
  "bcrypt (Secure password hashing)",
  "REST APIs",
  "Model–View–Controller (MVC)",
  "Azure DevOps",
  "Socket.IO",
  "SHARE POINT FRAMEWORK",
  "Server-Side Rendering (SSR) with EJS",
  "GitHub",
  "React Router",
  "Material-UI, Chakra-UI, React-Bootstrap",
  "Styled Components - Sass",
  "Microsoft Windows Series, Linux",
  "HTML, CSS",
  "Problem-Solving",
  "Strong Communication",
  "Zustand",
  "TailwindCSS",
  "Framer Motion",
  "React Query",
]