export const SkillCategories = {
  Frontend: [
    { label: "React.js", emoji: "⚛️" },
    { label: "TypeScript", emoji: "🔷" },
    { label: "JavaScript", emoji: "🟨" },
    { label: "HTML & CSS", emoji: "🌐" },
    { label: "TailwindCSS", emoji: "💨" },
    { label: "Framer Motion", emoji: "🎬" },
    { label: "Redux Toolkit", emoji: "🔄" },
    { label: "Zustand", emoji: "🐻" },
    { label: "React Query", emoji: "🔃" },
    { label: "Fluent UI", emoji: "🎨" },
    { label: "Material-UI", emoji: "🖼️" },
    { label: "Chakra-UI", emoji: "⚡" },
    { label: "React-Bootstrap", emoji: "🅱️" },
    { label: "Styled Components", emoji: "💅" },
    { label: "Sass", emoji: "🎀" },
    { label: "React Router", emoji: "🗺️" },
    { label: "Vite", emoji: "⚡" },
  ],
  Backend: [
    { label: "Node.js", emoji: "🟩" },
    { label: "Express.js", emoji: "🚂" },
    { label: "GraphQL", emoji: "🔺" },
    { label: "REST APIs", emoji: "🛠️" },
    { label: "MVC Pattern", emoji: "🏗️" },
    { label: "SSR with EJS", emoji: "📄" },
    { label: "MongoDB", emoji: "🍃" },
    { label: "PostgreSQL", emoji: "🐘" },
    { label: "Redis", emoji: "🔴" },
    { label: "Socket.IO", emoji: "🔌" },
    { label: "WebRTC", emoji: "📡" },
    { label: "JWT / RBAC", emoji: "🔑" },
    { label: "bcrypt", emoji: "🔒" },
    { label: "Mongoose", emoji: "🔗" },
  ],
  "Cloud & AI": [
    { label: "Google Vertex AI", emoji: "🧠" },
    { label: "Vision AI (OCR)", emoji: "👁️" },
    { label: "OpenAI API", emoji: "🤖" },
    { label: "Cloudinary", emoji: "☁️" },
    { label: "Stripe", emoji: "💳" },
    { label: "Azure DevOps", emoji: "🔵" },
    { label: "SharePoint FX", emoji: "📦" },
  ],
  "Testing & Tools": [
    { label: "Playwright", emoji: "🎭" },
    { label: "Jest", emoji: "🃏" },
    { label: "React Testing Library", emoji: "🧪" },
    { label: "Supertest", emoji: "🔬" },
    { label: "Docker", emoji: "🐳" },
    { label: "Kubernetes", emoji: "☸️" },
    { label: "CI/CD", emoji: "⚙️" },
    { label: "Git & GitHub", emoji: "🐙" },
    { label: "Postman", emoji: "📬" },
    { label: "Linux", emoji: "🐧" },
  ],
  "Soft Skills": [
    { label: "System Design", emoji: "🏗️" },
    { label: "Problem-Solving", emoji: "🧩" },
    { label: "Strong Communication", emoji: "💬" },
    { label: "Team Leadership", emoji: "🤝" },
  ],
};

// backward compat
export const Skills = Object.values(SkillCategories).flat().map((s) => s.label);